pipeline {
    agent any
    environment {
        ANSIBLE_PLAYBOOK_PATH = '/etc/ansible/playbooks/auth.yml'
        ANSIBLE_INVENTORY_PATH = '/etc/ansible/aws_ec2.yml'
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
    }

    stages {
        stage('Clone repository') {
            steps {
                git branch: 'Development', url: 'https://github.com/Sebastian-Montoya-Z/RampUp_login'
            }
        }

        stage('Build image') {
            steps{
                script {
                    sh 'ls'
                    sh 'docker build ./auth-api -t sebastianmontoyaz/rampup-perfi:auth --no-cache'
                }
            }
        }

        stage('push image') {
            steps{
                script {
                    sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                    sh ' docker push sebastianmontoyaz/rampup-perfi:auth'
                }
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                script{
                    sh 'ls'
                }
                ansiblePlaybook(
                    playbook: "${env.ANSIBLE_PLAYBOOK_PATH}",
                    inventory: "${env.ANSIBLE_INVENTORY_PATH}",
                    extras: '-e ilb=internal-SMZ-lb-internal-338455689.us-east-1.elb.amazonaws.com'
                )
            }
        }
    }
}